apiRules:
- exclude:
    uidRegex: ^ECellDive\.CustomEditors$
    type: Namespace
- exclude:
    uidRegex: ^ECellDive\.Tutorials$
    type: Namespace
- exclude:
    uidRegex: ^ECellDive\.Interfaces.ITutorial*
    type: Interface