name: ECellDive documentation

on:
  push:
    branches:
      - main

jobs:

  generate_plantuml:
    runs-on: ubuntu-latest #Required to have correct paths
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: example
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build the documentation
  build:
    needs: generate_plantuml # Required to have all generated diagram svg files
    runs-on: windows-latest # Required by DocFX
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install DocFX
        #run: choco install -y docfx
        run: dotnet tool install -g docfx

      - name: Build
        run: docfx DocFX/docfx.json

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs # Must equals the 'build.dest' value on your docfx.json

  # Deploy the generated documentation to the gh-pages branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs